#+TITLE: Languages and Grammars \newline Buffalo
#+AUTHORS: Sam Graham, Jake Casperson
#+startup: beamer
#+LATEX_CLASS: beamer
#+LATEX_CLASS_OPTIONS: [presentation]
#+BEAMER_THEME: default
#+BEAMER_FRAME_LEVEL: 2
#+OPTIONS: toc:nil

* Sam Graham

#+ATTR_BEAMER: :overlay +-
- https://github.com/Sam-Gram
- https://www.hackerrank.com/samgraham
- http://www.codewars.com/users/Sam-Gram
- http://stackoverflow.com/users/2521049/sam-graham

* Jacob Casperson
#+ATTR_BEAMER: :overlay +-
- https://github.com/jataca

* Preston Price
#+ATTR_BEAMER: :overlay +-
- https://github.com/prestonprice57
- https://www.hackerrank.com/prestonprice57
- https://itunes.apple.com/us/developer/preston-price/id972357986


* Time flies like an arrow [1]

#+ATTR_BEAMER: :overlay +-
- Measure the speed of flies like you would measure that of an arrow
- Measure the speed of flies like an arrow would
- Measure the speed of flies that are like arrows
- Time moves in a way an arrow would.
- Certain flying insects, "time flies," enjoy an arrow.

* What is a language? 

A set of strings. (Not the world's best definition ) \newline
For example, a string in the English language would be: \newline
Buffalo buffalo Buffalo buffalo buffalo buffalo Buffalo buffalo.

* What is a grammar? 

The rules that generate a given set of strings.

* A simple example [2]
A \rightarrow 0A1 \newline
A \rightarrow B \newline
B \rightarrow # \newline

* An English grammer (Subset) [2]

\scriptsize
\langle SENTENCE \rangle \rightarrow \langle NOUN-PHRASE \rangle \langle VERB-PHRASE \rangle \newline
\langle NOUN-PHRASE \rangle \rightarrow \langle CMPLX-NOUN \rangle \vert \langle CMPLX-NOUN \rangle \langle PREP-PHRASE \rangle \newline
\langle VERB-PHRASE \rangle \rightarrow \langle CMPLX-VERB \rangle \vert \langle CMPLX-VERB \rangle \langle PREP-PHRASE \rangle \newline
\langle PREP-PHRASE \rangle \rightarrow \langle PREP \rangle \langle CMPLX-NOUN \rangle \newline
\langle CMPLX-NOUN \rangle \rightarrow \langle ARTICLE \rangle \langle NOUN \rangle \newline
\langle ARTICLE \rangle \rightarrow a \vert the \newline
\langle NOUN \rangle \rightarrow boy \vert girl \vert flower \newline
\langle VERB \rangle \rightarrow touches \vert likes \vert sees \newline
\langle PREP \rangle \rightarrow with

* What use is this in the world of computers?

https://www.youtube.com/watch?v=qOpW5VN2j2Q


[1] \tiny https://en.wikipedia.org/wiki/Time_flies_like_an_arrow;_fruit_flies_like_a_banana
[2] \tiny "Introduction to the Theory of Computation" by Michael Sipser, Second Edition.
